export const styles = {
  IMAGE_FONT_SIZE: 30,
  IMAGE_TEXT_COLOR: "#ffffff",
  IMAGE_MARGIN_HORIZONTAL: 100,
  IMAGE_MARGIN_TOP: 165,
  IMAGEM_MARGIM_LEFT: 100,
  IMAGEM_MARGIM_RIGHT: -240,
  IMAGE_MARGIN_BOTTOM: 50,
  SPACE_BETWEEN_LETTERS: 4,
  SPACE_BETWEEN_PARAGRAPH: 15,
  FONT_WEIGHT: 500,
  FONT_STYLE: "normal",
  IMAGE_FONT_NAME: "Roboto-Medium.ttf",
  IMAGE_FONT_FILE: "FONTS/Roboto-Medium.ttf"
}
